### ISSUE TITLE
link on Open Exchange is broken

### ISSUE THREAD

**Issue by spdegabrielle** [ZitRos/cache-visual-editor#2]
Hi, 

Congratulation on 'App of the week'

I just noticed the download links on the Open Oxchange page for this app are both failing:

- DOWNLOAD (button): https://github.com/intersystems-community/objectscript-visual-editor/releases
-  'Download the latest release from **here**' : https://github.com/intersystems-ru/objectscript-visual-editor/releases

see https://openexchange.intersystems.com/package/ObjectScript-Visual-Editor 

**Thank you for building and sharing this.**

Stephen

PS: also logged at https://community.intersystems.com/post/objectscript-visual-editor-github-repo

**Comment by nikitaeverywhere** [comment]
Hello @spdegabrielle!

Thank you! Thanks for reporting this! :) Fill try to fix this ASAP.

This is the valid link to downloads: https://github.com/intersystems-ru/cache-visual-editor/releases

**Comment by nikitaeverywhere** [comment]
Now fixed. Thanks! See this thread: https://community.intersystems.com/post/objectscript-visual-editor-github-repo
